site_name: Mantl
site_url: https://mantl.io
repo_url: https://github.com/CiscoCloud/mantl
copyright: "2016 Cisco Systems"
markdown_extensions:
        - extra
        - toc:
                permalink: True
pages:
        - 'index.md'
        - "Core Components":
                - "core/consul.md"
        - "Addon Components":
                - 'addons/kafka.md'
theme: readthedocs
