---
calico_version: 0.15.0

calico_image: calico/node
calico_image_tag: v{{ calico_version }}

bintray_baseurl: "https://bintray.com/artifact/download/asteris"
calico_binary: "{{ bintray_baseurl }}/mantl-rpm/calico-{{ calico_version }}-1.x86_64.rpm"

etcd_service_name: etcd.service.consul
etcd_client_port: 2379

calico_etcdaddr: "{{ private_ipv4 }}:{{ etcd_client_port }}"

calico_network: 192.168.0.0/16

calico_profile: dev
