apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:{{ kube_version }}
    command:
    - /hyperkube
    - proxy
    - --master=https://kubernetes.service.consul:{{ kube_master_port }}
    - --kubeconfig=/etc/kubernetes/master.kubeconfig
    - --proxy-mode=iptables
    - --v={{kube_log_level}}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: etc-kubernetes
