- name: Calico directory for cni config
  sudo: yes
  file:
    path: /etc/cni/net.d
    state: directory
  tags:
    - calico

- name: Calico cni config for kubernetes
  sudo: yes
  template:
    src: calico-plugin.conf
    dest: /etc/cni/net.d/10-calico.conf
  tags:
    - calico
